Repository cardo-usa/usa, pull requests merged in 2023-08, with the labels that each got.

#9 `Header` コンポーネントを実装
  apps/website/package.json
  apps/website/src/app/layout.tsx
  apps/website/src/component/user-icon/index.ts
  apps/website/src/component/user-icon/user-icon.presenter.tsx
  apps/website/src/component/user-icon/user-icon.story.tsx
  apps/website/src/model/account-setting.ts
  apps/website/src/module/root/ui/layout/header/header.container.tsx
  apps/website/src/module/root/ui/layout/header/header.presenter.tsx
  apps/website/src/module/root/ui/layout/header/header.story.tsx
  apps/website/src/module/root/ui/layout/header/index.ts
  apps/website/src/state/account-setting/account-setting.atom.ts
  apps/website/src/state/account-setting/account-setting.hook.tsx
  apps/website/src/state/account-setting/index.ts
  apps/website/src/state/atom-keys.ts
  packages/core/asset/brand/logo.svg
  packages/core/icon/book-icon/book-icon.presenter.tsx
  packages/core/icon/book-icon/book-icon.story.tsx
  packages/core/icon/book-icon/index.tsx
  packages/design-token/index.ts
  packages/tailwind/src/config.ts
  pnpm-lock.yaml
Labels: 🍱 asset, 📦️ build, 🔧 config, ✨ feature

#18 api app をセットアップ
  .devcontainer/devcontainer.json
  .github/filter.yaml
  .vscode/settings.json
  apps/api/.env.example
  apps/api/.eslintignore
  apps/api/.eslintrc.cjs
  apps/api/.gitignore
  apps/api/.lintstagedrc.cjs
  apps/api/.prettierignore
  apps/api/.prettierrc.cjs
  apps/api/jest.config.cjs
  apps/api/package.json
  apps/api/src/app/app.module.ts
  apps/api/src/common/constant/injection-token.ts
  apps/api/src/common/dto/enum/card-color.enum.ts
  apps/api/src/common/dto/enum/card-type.enum.ts
  apps/api/src/common/dto/object/card.object.ts
  apps/api/src/common/model/card.model.ts
  apps/api/src/config/env/env.module.ts
  apps/api/src/config/env/env.service.ts
  apps/api/src/config/env/validate.ts
  apps/api/src/config/graphql/graphql-config.module.ts
  apps/api/src/infra/prisma/prisma.module.ts
  apps/api/src/infra/prisma/prisma.service.ts
  apps/api/src/infra/prisma/schema.prisma
  apps/api/src/main.ts
  apps/api/src/module/modules.ts
  apps/api/src/module/user/controller/dto/enum/game-state.enum.ts
  apps/api/src/module/user/controller/dto/enum/icon-background-color.enum.ts
  apps/api/src/module/user/controller/dto/enum/role.enum.ts
  apps/api/src/module/user/controller/dto/input/user-update-game-state.input.ts
  apps/api/src/module/user/controller/dto/input/user-update.input.ts
  apps/api/src/module/user/controller/dto/input/user-where-unique.input.ts
  apps/api/src/module/user/controller/dto/object/user-object.ts
  apps/api/src/module/user/controller/user-mutation.resolver.ts
  apps/api/src/module/user/controller/user-query.resolver.ts
  apps/api/src/module/user/domain/user.model.ts
  apps/api/src/module/user/repository/impl/user.repository.ts
  apps/api/src/module/user/repository/user.repository.ts
  apps/api/src/module/user/use-case/impl/user.use-case.ts
  apps/api/src/module/user/use-case/user.use-case.ts
  apps/api/src/module/user/user.module.ts
  apps/api/tsconfig.build.json
  apps/api/tsconfig.json
  docker/api/Dockerfile.production
  packages/eslint/eslint-config-usa-esm/index.cjs
  packages/eslint/eslint-config-usa-node/index.cjs
  packages/eslint/package.json
  packages/tsconfig/package.json
  packages/tsconfig/tsconfig.node.json
  pnpm-lock.yaml
Labels: 📦️ build, 🦺 ci, 🔧 config, 🚑️ critical, ✨ feature

#21 フォントが読み込まれないバグを修正
  apps/website/src/module/root/ui/layout/header/header.presenter.tsx
  packages/tailwind/src/config.ts
Labels: 🐛 bug, 🔧 config

#24 api の production 用 Dockerfile で turbo の remote cache を使用できるように修正
  docker/api/Dockerfile.production
Labels: 📦️ build

#26 `verifyCanJoinRoom` Query を実装
  apps/api/src/app/app.module.ts
  apps/api/src/common/constant/injection-token.ts
  apps/api/src/module/index.ts
  apps/api/src/module/modules.ts
  apps/api/src/module/room/controller/dto/enum/room-game-state.enum.ts
  apps/api/src/module/room/controller/dto/input/room-where-unique.input.ts
  apps/api/src/module/room/controller/dto/object/room-object.ts
  apps/api/src/module/room/controller/room-query.resolver.ts
  apps/api/src/module/room/domain/room.model.ts
  apps/api/src/module/room/repository/impl/room.repository.ts
  apps/api/src/module/room/repository/room.repository.ts
  apps/api/src/module/room/room.module.ts
  apps/api/src/module/room/use-case/impl/room.use-case.ts
  apps/api/src/module/room/use-case/room.use-case.ts
  apps/api/src/module/user/controller/dto/enum/user-game-state.enum.ts
  apps/api/src/module/user/controller/dto/input/user-update-game-state.input.ts
  apps/api/src/module/user/controller/dto/input/user-update.input.ts
  apps/api/src/module/user/controller/dto/object/user-object.ts
  apps/api/src/module/user/domain/user.model.ts
  packages/eslint/eslint-config-usa-node/index.cjs
Labels: 🔧 config, ✨ feature, ♻ refactor

#28 `createRoom` Mutation を実装
  .github/workflows/app-test.yaml
  .github/workflows/graphql-deploy-apollo-studio.yaml
  apps/api/package.json
  apps/api/src/app/app.module.ts
  apps/api/src/cache/base.dataloader.ts
  apps/api/src/cache/cache.module.ts
  apps/api/src/cache/data-loader-cache.service.ts
  apps/api/src/infra/prisma/schema.prisma
  apps/api/src/module/room/controller/dto/object/room.object.ts
  apps/api/src/module/room/controller/room-mutation.resolver.ts
  apps/api/src/module/room/controller/room.resolver.ts
  apps/api/src/module/room/dataloader/room-users.dataloader.ts
  apps/api/src/module/room/dataloader/room.dataloader.ts
  apps/api/src/module/room/repository/impl/room.repository.ts
  apps/api/src/module/room/repository/room.repository.ts
  apps/api/src/module/room/room.module.ts
  apps/api/src/module/room/use-case/impl/room.use-case.ts
  apps/api/src/module/room/use-case/room.use-case.ts
  apps/api/src/module/user/controller/dto/input/user-account-setting.input.ts
  apps/api/src/module/user/controller/dto/object/user.object.ts
  apps/api/src/module/user/controller/user-mutation.resolver.ts
  apps/api/src/module/user/controller/user-query.resolver.ts
  apps/api/src/module/user/controller/user.resolver.ts
  apps/api/src/module/user/domain/user.model.ts
  apps/api/src/module/user/repository/impl/user.repository.ts
  apps/api/src/module/user/repository/user.repository.ts
  apps/api/src/module/user/user.module.ts
  package.json
  pnpm-lock.yaml
Labels: ✨ feature, ♻ refactor

#30 `joinRoom` Mutation を実装
  apps/api/src/module/user/controller/dto/input/user-update-game-state.input.ts
  apps/api/src/module/user/controller/user-mutation.resolver.ts
  apps/api/src/module/user/use-case/impl/user.use-case.ts
  apps/api/src/module/user/use-case/user.use-case.ts
Labels: ⚰️ delete, ✨ feature

#32 `UpdatedRoomAttenders` Subscription を実装
  apps/api/src/app/app.module.ts
  apps/api/src/common/constant/pubsub.ts
  apps/api/src/common/service/cache/base.dataloader.ts
  apps/api/src/common/service/cache/cache.module.ts
  apps/api/src/common/service/cache/data-loader-cache.service.ts
  apps/api/src/common/service/env/env.module.ts
  apps/api/src/common/service/env/env.service.ts
  apps/api/src/common/service/env/validate.ts
  apps/api/src/common/service/pubsub/pubsub.module.ts
  apps/api/src/common/service/pubsub/pubsub.service.ts
  apps/api/src/config/graphql/graphql-config.module.ts
  apps/api/src/infra/prisma/prisma.module.ts
  apps/api/src/infra/prisma/prisma.service.ts
  apps/api/src/main.ts
  apps/api/src/module/room/controller/dto/input/room-where-unique.input.ts
  apps/api/src/module/room/controller/dto/object/room.object.ts
  apps/api/src/module/room/dataloader/room-users.dataloader.ts
  apps/api/src/module/room/dataloader/room.dataloader.ts
  apps/api/src/module/room/use-case/impl/room.use-case.ts
  apps/api/src/module/user/controller/dto/input/user-update.input.ts
  apps/api/src/module/user/controller/dto/input/user-where-unique.input.ts
  apps/api/src/module/user/controller/dto/object/user.object.ts
  apps/api/src/module/user/controller/user-mutation.resolver.ts
  apps/api/src/module/user/controller/user-subscription.resolver.ts
  apps/api/src/module/user/repository/impl/user.repository.ts
  apps/api/src/module/user/repository/user.repository.ts
  apps/api/src/module/user/use-case/impl/user.use-case.ts
  apps/api/src/module/user/use-case/user.use-case.ts
  apps/api/src/module/user/user.module.ts
Labels: ✨ feature, ♻ refactor

#39 `updatedRoom` Subscription を実装
  .github/workflows/graphql-deploy-apollo-studio.yaml
  apps/api/src/common/constant/injection-token.ts
  apps/api/src/common/constant/pubsub.ts
  apps/api/src/module/room/controller/dto/input/room-update-game-state.input.ts
  apps/api/src/module/room/controller/dto/input/room-update.input.ts
  apps/api/src/module/room/controller/room-mutation.resolver.ts
  apps/api/src/module/room/controller/room-subscription.resolver.ts
  apps/api/src/module/room/repository/impl/room.repository.ts
  apps/api/src/module/room/repository/room.repository.ts
  apps/api/src/module/room/room.module.ts
  apps/api/src/module/room/use-case/impl/room-publish.use-case.ts
  apps/api/src/module/room/use-case/impl/room.use-case.ts
  apps/api/src/module/room/use-case/room-publish.use-case.ts
  apps/api/src/module/room/use-case/room.use-case.ts
  apps/api/src/module/user/controller/user-mutation.resolver.ts
  apps/api/src/module/user/controller/user-subscription.resolver.ts
  apps/api/src/module/user/use-case/impl/user.use-case.ts
  apps/api/src/module/user/use-case/user.use-case.ts
  apps/api/src/module/user/user.module.ts
Labels: ✨ feature

#44 トップページの作成(GraphQL未実装)
  apps/website/src/app/page.tsx
  apps/website/src/component/modal/account-setting/account-setting.presenter.tsx
  apps/website/src/component/user-icon/user-icon.presenter.tsx
  apps/website/src/module/root/ui/layout/header/header.presenter.tsx
  packages/core/asset/brand/carrot.svg
  packages/core/asset/top/bg-cards.svg
Labels: ✨ feature

#54 トップページの作成(GraphQL実装)
  apps/website/src/app/page.tsx
  apps/website/src/infra/graphql/document/create-room.gql
  apps/website/src/module/root/ui/page/index.tsx
  apps/website/src/module/root/ui/page/page.presenter.tsx
  apps/website/src/state/account-setting/account-setting.atom.ts
  apps/website/src/state/account-setting/account-setting.hook.tsx
  apps/website/src/state/atom-keys.ts
  apps/website/src/state/client-to-server-data/client-to-server-data.converter.ts
  apps/website/src/state/client-to-server-data/index.ts
  apps/website/src/state/server-to-client-data/index.ts
  apps/website/src/state/server-to-client-data/server-to-client-data.converter.ts
Labels: 📝 document, ✨ feature

#50 `initializeGame` Mutation を実装
  apps/api/src/common/constant/initial-cards.ts
  apps/api/src/common/model/card.model.ts
  apps/api/src/module/room/controller/room-mutation.resolver.ts
  apps/api/src/module/room/use-case/impl/room.use-case.ts
  apps/api/src/module/room/use-case/room.use-case.ts
  apps/website/graphql.schema.json
Labels: ✨ feature

#56 `drawCardFromDeckCards` Mutation を実装
  apps/api/src/common/constant/initial-cards.ts
  apps/api/src/common/dto/object/card.object.ts
  apps/api/src/common/model/card.model.ts
  apps/api/src/infra/prisma/schema.prisma
  apps/api/src/module/room/controller/room.resolver.ts
  apps/api/src/module/user/controller/user-mutation.resolver.ts
  apps/api/src/module/user/use-case/impl/user.use-case.ts
  apps/api/src/module/user/use-case/user.use-case.ts
  apps/website/graphql.schema.json
Labels: ✨ feature

#59 `putHandCardToFieldCards` Mutation を実装
  apps/api/src/module/room/controller/room.resolver.ts
  apps/api/src/module/room/use-case/impl/room.use-case.ts
  apps/api/src/module/user/controller/dto/object/user.object.ts
  apps/api/src/module/user/controller/user-mutation.resolver.ts
  apps/api/src/module/user/domain/user.model.ts
  apps/api/src/module/user/repository/impl/user.repository.ts
  apps/api/src/module/user/repository/user.repository.ts
  apps/api/src/module/user/use-case/impl/user.use-case.ts
  apps/api/src/module/user/use-case/user.use-case.ts
  apps/website/graphql.schema.json
Labels: ✨ feature

#61 `getResult` Query と `exitRoom` Mutation を実装
  apps/api/src/module/room/controller/dto/input/room-update.input.ts
  apps/api/src/module/room/controller/dto/object/room.object.ts
  apps/api/src/module/room/controller/room-query.resolver.ts
  apps/api/src/module/room/controller/room.resolver.ts
  apps/api/src/module/room/domain/room.model.ts
  apps/api/src/module/room/repository/impl/room.repository.ts
  apps/api/src/module/room/repository/room.repository.ts
  apps/api/src/module/room/use-case/impl/room.use-case.ts
  apps/api/src/module/room/use-case/room.use-case.ts
  apps/api/src/module/user/controller/user-mutation.resolver.ts
  apps/api/src/module/user/repository/impl/user.repository.ts
  apps/api/src/module/user/repository/user.repository.ts
  apps/api/src/module/user/use-case/impl/user.use-case.ts
  apps/api/src/module/user/use-case/user.use-case.ts
  apps/website/graphql.schema.json
Labels: ✨ feature
